### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by danielboothcloud** [chkpwd/alfred-ente-auth#22]
I have installed the workflow and have set up the ente auth cli version v0.2.2 however, when I attempt to import the OTP to alfredI see no results.

I can verify my ente has been exported via the CLI using _ente account list_ command: 
/Users/danielbooth/.ente

I also have python3 installed on my machine.

**Comment by chkpwd** [comment]
Hey @danielboothcloud, it would be great to have a bit more insight into your setup to determine what's causing the issue.

1. Are you able to see your exported accounts when doing a manual export? (e.g. `ente export`)
2. Any errors appear if you run the Alfred workflow in debug mode?

**Comment by danielboothcloud** [comment]
Hi,

Thanks for your prompt reply. I was not aware of the Alfred debug mode, and using it helped me further diagnose the issue.

Essentially, I set the binary path to ~/bin/ente. However, this did not seem to work because it did not recognize the ~ as my home directory.

I had previously considered this possibility but only ended up changing my ente export path to the absolute path and not the binary path.

The only caveat to this is that the script seems to interpret the ~ correctly when setting the export path but requires the absolute path when setting the binary path.

Thanks again for your help!

**Comment by chkpwd** [comment]
Thank you for submitting an issue, glad you caught this. The next release should allow this behavior.
