### ISSUE TITLE
Accounts with the same service name not appearing

### ISSUE THREAD

**Issue by SoPat712** [chkpwd/alfred-ente-auth#24]
I have TOTP enabled for three reddit accounts, but only one shows up in alfred

![CleanShot 2024-12-10 at 14 02 56](https://github.com/user-attachments/assets/c20c7de7-6591-4bcc-bbd0-e810109278a8)
![CleanShot 2024-12-10 at 14 03 23](https://github.com/user-attachments/assets/fd6e0946-d141-40a0-a0a9-6c793b6f1e4c)

**Comment by chkpwd** [comment]
Fixed in latest release.
